### ISSUE TITLE
accuracies

### ISSUE THREAD

**Issue by somiyaa** [anujdutt9/Handwritten-Digit-Recognition-using-Deep-Learning#3]
hi anuj

There is no accuracy in the summary.log file. whats wrong ?

**Comment by anujdutt9** [comment]
Hi @somiyaa can you please give some more explanation? For which ML Technique code you are not getting the accuracy in the summary.log file?

**Comment by somiyaa** [comment]
please see the attached screenshot. 
![image](https://user-images.githubusercontent.com/29824578/38465737-429f56ce-3b3d-11e8-9dda-0215e54d2586.png)

**Comment by somiyaa** [comment]
please see the attached screenshot. 
![image](https://user-images.githubusercontent.com/29824578/38465770-a75f9a56-3b3d-11e8-8dcd-f074633021ec.png)

I am not getting accuracy for all the four techniques. I am only getting the confusion matrix for validation data for KNN, RFC and SVM but not for CNN.

**Comment by anujdutt9** [comment]
Hi @somiyaa, if you see the code, the summary is written to the file only after "Confusion Matrix for Test Data" image is shown. For that, you need to close the image above and refresh the folder. Then you should be able to see the summary. If you see in the code, every file has a statement in the end as 
"sys.stdout = old_stdout
log_file.close()"

These lines write to the log file and close it. So, until your code reaches here, you'll have to wait and save and close the images as they get plotted.
Otherwise, the code works fine. I have tested it again now.
